include "application.conf"

ktor {
    development = false
}

appfood {
    environment = "prod"

    cors {
        // Surcharge par variable d'environnement en production
        allowedHosts = ${?CORS_ALLOWED_HOSTS}
    }
}
